//! `.claudeignore` generator — produces stack-aware ignore patterns for Claude Code.
//!
//! Detects the project's tech stack and generates optimized `.claudeignore` patterns
//! that exclude build artifacts, generated files, and dependencies from Claude's context.

use std::path::{Path, PathBuf};

use crate::config::detect_project_type;
use crate::model::ProjectType;

/// Result of generating a `.claudeignore` file.
#[derive(Debug, Clone)]
pub struct ClaudeIgnoreResult {
    /// The full content of the generated `.claudeignore` file.
    pub content: String,
    /// Number of non-comment, non-blank patterns.
    pub patterns_count: usize,
    /// Estimated number of files that would be ignored.
    pub estimated_files_ignored: usize,
}

/// Generate `.claudeignore` content based on the detected tech stack of a project.
pub fn generate_claudeignore(project_path: &Path) -> ClaudeIgnoreResult {
    let project_type = detect_project_type(project_path);
    generate_for_stack(project_path, project_type)
}

/// Generate patterns for a specific stack (also detects mixed/monorepo stacks).
fn generate_for_stack(project_path: &Path, primary_type: ProjectType) -> ClaudeIgnoreResult {
    let mut sections: Vec<String> = Vec::new();

    // Detect all stacks present (monorepo support)
    let mut stacks = vec![primary_type];
    for (marker, pt) in &[
        ("Cargo.toml", ProjectType::Rust),
        ("package.json", ProjectType::Node),
        ("go.mod", ProjectType::Go),
        ("pubspec.yaml", ProjectType::Flutter),
        ("requirements.txt", ProjectType::Python),
        ("pyproject.toml", ProjectType::Python),
        ("Dockerfile", ProjectType::Docker),
    ] {
        if project_path.join(marker).exists() && !stacks.contains(pt) {
            stacks.push(*pt);
        }
    }

    // Header
    sections.push(
        "# .claudeignore — Generated by Void Stack\n\
         # Excludes build artifacts, generated files, and dependencies\n\
         # to reduce Claude Code token consumption."
            .to_string(),
    );

    for stack in &stacks {
        match stack {
            ProjectType::Rust => {
                sections.push(format!(
                    "\n# Rust\n{}",
                    ["target/", "Cargo.lock", "lcov.info", "**/*.log",].join("\n")
                ));
            }
            ProjectType::Go => {
                sections.push(format!(
                    "\n# Go\n{}",
                    [
                        "vendor/",
                        "internal/pb/",
                        "**/*.pb.go",
                        "**/*.pb.gw.go",
                        "**/*_grpc.pb.go",
                        "coverage.out",
                        "tmp/",
                        "api/openapi/",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Flutter => {
                sections.push(format!(
                    "\n# Flutter / Dart\n{}",
                    [
                        "build/",
                        "**/*.g.dart",
                        "**/*.freezed.dart",
                        "**/pubspec.lock",
                        "android/",
                        "ios/",
                        "macos/",
                        "linux/",
                        "windows/",
                        "coverage/",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Node => {
                sections.push(format!(
                    "\n# Node / Next.js\n{}",
                    [
                        "node_modules/",
                        ".next/",
                        "out/",
                        "package-lock.json",
                        "yarn.lock",
                        "tsconfig.tsbuildinfo",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Python => {
                sections.push(format!(
                    "\n# Python\n{}",
                    [
                        ".venv/",
                        "__pycache__/",
                        "**/*.pyc",
                        "dist/",
                        ".pytest_cache/",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Docker | ProjectType::Unknown => {}
        }
    }

    // Always add Void Stack artifacts
    sections.push(format!(
        "\n# Void Stack artifacts\n{}",
        ["void-stack-analysis.md", "void-stack-diagrams.drawio"].join("\n")
    ));

    let content = format!("{}\n", sections.join("\n"));

    let patterns_count = content
        .lines()
        .filter(|l| {
            let t = l.trim();
            !t.is_empty() && !t.starts_with('#')
        })
        .count();

    let estimated_files_ignored = estimate_ignored_files(project_path, &content);

    ClaudeIgnoreResult {
        content,
        patterns_count,
        estimated_files_ignored,
    }
}

/// Rough estimate of how many files would be ignored by counting existing matches.
fn estimate_ignored_files(project_path: &Path, content: &str) -> usize {
    use crate::ignore::VoidIgnore;

    // Parse the generated content using the same ignore engine
    let ignore = VoidIgnore::from_content(content);

    // Walk up to 3 levels and count matches
    let mut count = 0;
    count_ignored_recursive(project_path, project_path, &ignore, &mut count, 0, 3);
    count
}

fn count_ignored_recursive(
    root: &Path,
    dir: &Path,
    ignore: &crate::ignore::VoidIgnore,
    count: &mut usize,
    depth: usize,
    max_depth: usize,
) {
    if depth > max_depth {
        return;
    }
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .to_string();

        if ignore.is_ignored(&relative) {
            // If it's a directory that's ignored, estimate its subtree
            if path.is_dir() {
                *count += estimate_dir_file_count(&path);
            } else {
                *count += 1;
            }
        } else if path.is_dir() {
            count_ignored_recursive(root, &path, ignore, count, depth + 1, max_depth);
        }
    }
}

/// Quick estimate of file count in a directory (non-recursive, capped).
fn estimate_dir_file_count(dir: &Path) -> usize {
    match std::fs::read_dir(dir) {
        Ok(entries) => entries.count().max(1),
        Err(_) => 1,
    }
}

/// Save generated `.claudeignore` content to the project root.
/// Also records the operation in the stats DB.
pub fn save_claudeignore(project_path: &Path, content: &str) -> std::io::Result<PathBuf> {
    let file_path = project_path.join(".claudeignore");
    std::fs::write(&file_path, content)?;

    // Record stats — use dir name as project identifier
    let project_name = project_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();
    let patterns = content
        .lines()
        .filter(|l| {
            let t = l.trim();
            !t.is_empty() && !t.starts_with('#')
        })
        .count();
    crate::stats::record_saving(crate::stats::TokenSavingsRecord {
        timestamp: chrono::Utc::now(),
        project: project_name,
        operation: "claudeignore".to_string(),
        lines_original: patterns,
        lines_filtered: 0,
        savings_pct: 100.0,
    });

    Ok(file_path)
}

/// Check if a `.claudeignore` file already exists in the project root.
pub fn claudeignore_exists(project_path: &Path) -> bool {
    project_path.join(".claudeignore").exists()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn setup_rust_project(dir: &Path) {
        fs::write(
            dir.join("Cargo.toml"),
            "[package]\nname = \"test\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
    }

    fn setup_node_project(dir: &Path) {
        fs::write(
            dir.join("package.json"),
            r#"{"name": "test", "version": "1.0.0"}"#,
        )
        .unwrap();
    }

    fn setup_go_project(dir: &Path) {
        fs::write(dir.join("go.mod"), "module example.com/test\n\ngo 1.21\n").unwrap();
    }

    fn setup_python_project(dir: &Path) {
        fs::write(dir.join("requirements.txt"), "flask==3.0.0\n").unwrap();
    }

    fn setup_flutter_project(dir: &Path) {
        fs::write(
            dir.join("pubspec.yaml"),
            "name: test\ndescription: A test project\n",
        )
        .unwrap();
    }

    // ── Stack detection tests ────────────────────────────────

    #[test]
    fn test_rust_project() {
        let dir = tempfile::tempdir().unwrap();
        setup_rust_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("target/"));
        assert!(result.content.contains("Cargo.lock"));
        assert!(result.content.contains("lcov.info"));
        assert!(result.content.contains("# Rust"));
        assert!(result.patterns_count >= 4);
    }

    #[test]
    fn test_node_project() {
        let dir = tempfile::tempdir().unwrap();
        setup_node_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("node_modules/"));
        assert!(result.content.contains(".next/"));
        assert!(result.content.contains("package-lock.json"));
        assert!(result.content.contains("yarn.lock"));
        assert!(result.content.contains("# Node"));
    }

    #[test]
    fn test_go_project() {
        let dir = tempfile::tempdir().unwrap();
        setup_go_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("vendor/"));
        assert!(result.content.contains("**/*.pb.go"));
        assert!(result.content.contains("coverage.out"));
        assert!(result.content.contains("api/openapi/"));
        assert!(result.content.contains("# Go"));
    }

    #[test]
    fn test_python_project() {
        let dir = tempfile::tempdir().unwrap();
        setup_python_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains(".venv/"));
        assert!(result.content.contains("__pycache__/"));
        assert!(result.content.contains("**/*.pyc"));
        assert!(result.content.contains("dist/"));
        assert!(result.content.contains("# Python"));
    }

    #[test]
    fn test_flutter_project() {
        let dir = tempfile::tempdir().unwrap();
        setup_flutter_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("build/"));
        assert!(result.content.contains("**/*.g.dart"));
        assert!(result.content.contains("**/*.freezed.dart"));
        assert!(result.content.contains("android/"));
        assert!(result.content.contains("ios/"));
        assert!(result.content.contains("# Flutter"));
    }

    #[test]
    fn test_unknown_project() {
        let dir = tempfile::tempdir().unwrap();
        let result = generate_claudeignore(dir.path());
        // Should still have Void Stack artifacts
        assert!(result.content.contains("void-stack-analysis.md"));
        assert!(result.content.contains("void-stack-diagrams.drawio"));
        assert!(result.patterns_count >= 2);
    }

    // ── Always-present patterns ──────────────────────────────

    #[test]
    fn test_always_includes_void_stack_artifacts() {
        let dir = tempfile::tempdir().unwrap();
        setup_rust_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("void-stack-analysis.md"));
        assert!(result.content.contains("void-stack-diagrams.drawio"));
    }

    #[test]
    fn test_header_present() {
        let dir = tempfile::tempdir().unwrap();
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("# .claudeignore"));
        assert!(result.content.contains("Generated by Void Stack"));
    }

    // ── Monorepo / mixed stack ───────────────────────────────

    #[test]
    fn test_monorepo_rust_and_node() {
        let dir = tempfile::tempdir().unwrap();
        setup_rust_project(dir.path());
        setup_node_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("# Rust"));
        assert!(result.content.contains("# Node"));
        assert!(result.content.contains("target/"));
        assert!(result.content.contains("node_modules/"));
    }

    #[test]
    fn test_monorepo_python_and_go() {
        let dir = tempfile::tempdir().unwrap();
        setup_python_project(dir.path());
        setup_go_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("# Python"));
        assert!(result.content.contains("# Go"));
        assert!(result.content.contains(".venv/"));
        assert!(result.content.contains("vendor/"));
    }

    #[test]
    fn test_monorepo_all_stacks() {
        let dir = tempfile::tempdir().unwrap();
        setup_rust_project(dir.path());
        setup_node_project(dir.path());
        setup_go_project(dir.path());
        setup_python_project(dir.path());
        setup_flutter_project(dir.path());
        let result = generate_claudeignore(dir.path());
        assert!(result.content.contains("# Rust"));
        assert!(result.content.contains("# Node"));
        assert!(result.content.contains("# Go"));
        assert!(result.content.contains("# Python"));
        assert!(result.content.contains("# Flutter"));
        // Should have patterns from all stacks plus void-stack artifacts
        assert!(result.patterns_count >= 20);
    }

    // ── Save / exists ────────────────────────────────────────

    #[test]
    fn test_save_claudeignore() {
        let dir = tempfile::tempdir().unwrap();
        assert!(!claudeignore_exists(dir.path()));
        let path = save_claudeignore(dir.path(), "test content\n").unwrap();
        assert!(path.exists());
        assert!(claudeignore_exists(dir.path()));
        let saved = fs::read_to_string(&path).unwrap();
        assert_eq!(saved, "test content\n");
    }

    #[test]
    fn test_claudeignore_exists_false() {
        let dir = tempfile::tempdir().unwrap();
        assert!(!claudeignore_exists(dir.path()));
    }

    #[test]
    fn test_claudeignore_exists_true() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".claudeignore"), "test").unwrap();
        assert!(claudeignore_exists(dir.path()));
    }

    // ── Integration: generate + save + verify ────────────────

    #[test]
    fn test_generate_and_save() {
        let dir = tempfile::tempdir().unwrap();
        setup_rust_project(dir.path());

        let result = generate_claudeignore(dir.path());
        let path = save_claudeignore(dir.path(), &result.content).unwrap();

        assert!(path.exists());
        let saved = fs::read_to_string(&path).unwrap();
        assert_eq!(saved, result.content);
        assert!(saved.contains("target/"));
    }

    // ── Estimated files ignored ──────────────────────────────

    #[test]
    fn test_estimated_files_with_node_modules() {
        let dir = tempfile::tempdir().unwrap();
        setup_node_project(dir.path());

        // Create node_modules with some files
        let nm = dir.path().join("node_modules");
        fs::create_dir(&nm).unwrap();
        fs::write(nm.join("a.js"), "").unwrap();
        fs::write(nm.join("b.js"), "").unwrap();
        fs::write(nm.join("c.js"), "").unwrap();

        let result = generate_claudeignore(dir.path());
        assert!(result.estimated_files_ignored >= 3);
    }

    #[test]
    fn test_estimated_files_empty_project() {
        let dir = tempfile::tempdir().unwrap();
        let result = generate_claudeignore(dir.path());
        assert_eq!(result.estimated_files_ignored, 0);
    }

    // ── Pattern count accuracy ───────────────────────────────

    #[test]
    fn test_patterns_count_excludes_comments() {
        let dir = tempfile::tempdir().unwrap();
        setup_rust_project(dir.path());
        let result = generate_claudeignore(dir.path());

        // Manually count non-comment, non-blank lines
        let manual_count = result
            .content
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .count();
        assert_eq!(result.patterns_count, manual_count);
    }

    #[test]
    fn test_no_duplicate_stacks() {
        let dir = tempfile::tempdir().unwrap();
        // Python can be detected via both requirements.txt and pyproject.toml
        fs::write(dir.path().join("requirements.txt"), "flask\n").unwrap();
        fs::write(
            dir.path().join("pyproject.toml"),
            "[project]\nname = \"test\"\n",
        )
        .unwrap();

        let result = generate_claudeignore(dir.path());
        // Should only have one Python section
        let python_count = result.content.matches("# Python").count();
        assert_eq!(python_count, 1);
    }
}
