//! `.voidignore` generator for semantic index quality.

use std::path::{Path, PathBuf};

/// Result of generating a `.voidignore` file optimized for semantic index quality.
#[derive(Debug, Clone)]
pub struct VoidIgnoreResult {
    pub content: String,
    pub patterns_count: usize,
}

/// Generate `.voidignore` content optimized for the vector index.
///
/// Unlike `.claudeignore` (which focuses on Claude Code token reduction), this
/// focuses on semantic index quality: excludes generated code, mocks, fixtures,
/// and config files that don't carry business-logic semantics.
pub fn generate_voidignore(project_path: &Path) -> VoidIgnoreResult {
    use crate::config::detect_project_type;
    use crate::model::ProjectType;

    let project_type = detect_project_type(project_path);

    let mut sections: Vec<String> = Vec::new();

    // Detect stacks
    let mut stacks = vec![project_type];
    for (marker, pt) in &[
        ("Cargo.toml", ProjectType::Rust),
        ("package.json", ProjectType::Node),
        ("go.mod", ProjectType::Go),
        ("pubspec.yaml", ProjectType::Flutter),
        ("requirements.txt", ProjectType::Python),
        ("pyproject.toml", ProjectType::Python),
    ] {
        if project_path.join(marker).exists() && !stacks.contains(pt) {
            stacks.push(*pt);
        }
    }

    sections.push(
        "# .voidignore — Generated by Void Stack\n\
         # Optimized for semantic index quality: excludes generated code,\n\
         # build artifacts, and files that don't carry business-logic semantics."
            .to_string(),
    );

    // Universal exclusions (always present)
    sections.push(format!(
        "\n# Build artifacts & dependencies\n{}",
        [
            "target/",
            "node_modules/",
            ".venv/",
            "venv/",
            "__pycache__/",
            "dist/",
            "build/",
            ".next/",
            ".nuxt/",
            ".dart_tool/",
            "vendor/",
            ".turbo/",
            "coverage/",
        ]
        .join("\n")
    ));

    // Generated code patterns
    sections.push(format!(
        "\n# Generated code\n{}",
        [
            "**/*.pb.rs",
            "**/*.pb.go",
            "**/*_pb2.py",
            "**/*_grpc.pb.go",
            "**/*.g.dart",
            "**/*.freezed.dart",
            "**/*.gen.go",
            "**/*.generated.ts",
            "**/*.d.ts",
        ]
        .join("\n")
    ));

    // Coverage & reporting
    sections.push(format!(
        "\n# Coverage & reports\n{}",
        ["lcov.info", "coverage.xml", "coverage.out", "**/*.lcov",].join("\n")
    ));

    for stack in &stacks {
        match stack {
            ProjectType::Rust => {
                sections.push(format!(
                    "\n# Rust specifics\n{}",
                    ["Cargo.lock", "**/*.log"].join("\n")
                ));
            }
            ProjectType::Go => {
                sections.push(format!(
                    "\n# Go specifics\n{}",
                    ["internal/pb/", "api/openapi/", "tmp/"].join("\n")
                ));
            }
            ProjectType::Flutter => {
                sections.push(format!(
                    "\n# Flutter platform dirs (no business logic)\n{}",
                    [
                        "android/",
                        "ios/",
                        "macos/",
                        "linux/",
                        "windows/",
                        "**/pubspec.lock",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Node => {
                sections.push(format!(
                    "\n# Node specifics\n{}",
                    [
                        "package-lock.json",
                        "yarn.lock",
                        "pnpm-lock.yaml",
                        "tsconfig.tsbuildinfo",
                        "out/",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Python => {
                sections.push(format!(
                    "\n# Python specifics\n{}",
                    ["**/*.pyc", ".pytest_cache/", "**/*.egg-info/"].join("\n")
                ));
            }
            ProjectType::Docker | ProjectType::Unknown => {}
        }
    }

    // Test fixtures & mocks (common noise for semantic search)
    sections.push(format!(
        "\n# Test fixtures & large data files\n{}",
        [
            "**/fixtures/",
            "**/testdata/",
            "**/__fixtures__/",
            "**/__snapshots__/",
        ]
        .join("\n")
    ));

    // Void Stack own artifacts
    sections.push(format!(
        "\n# Void Stack artifacts\n{}",
        ["void-stack-analysis.md", "void-stack-diagrams.drawio"].join("\n")
    ));

    let content = format!("{}\n", sections.join("\n"));

    let patterns_count = content
        .lines()
        .filter(|l| {
            let t = l.trim();
            !t.is_empty() && !t.starts_with('#')
        })
        .count();

    VoidIgnoreResult {
        content,
        patterns_count,
    }
}

/// Save generated `.voidignore` content to the project root.
pub fn save_voidignore(project_path: &Path, content: &str) -> std::io::Result<PathBuf> {
    let file_path = project_path.join(".voidignore");
    std::fs::write(&file_path, content)?;
    Ok(file_path)
}
