//! `.voidignore` generator for semantic index quality.

use std::path::{Path, PathBuf};

/// Result of generating a `.voidignore` file optimized for semantic index quality.
#[derive(Debug, Clone)]
pub struct VoidIgnoreResult {
    pub content: String,
    pub patterns_count: usize,
}

/// Generate `.voidignore` content optimized for the vector index.
///
/// Unlike `.claudeignore` (which focuses on Claude Code token reduction), this
/// focuses on semantic index quality: excludes generated code, mocks, fixtures,
/// and config files that don't carry business-logic semantics.
pub fn generate_voidignore(project_path: &Path) -> VoidIgnoreResult {
    use crate::config::detect_project_type;
    use crate::model::ProjectType;

    let project_type = detect_project_type(project_path);

    let mut sections: Vec<String> = Vec::new();

    // Detect stacks
    let mut stacks = vec![project_type];
    for (marker, pt) in &[
        ("Cargo.toml", ProjectType::Rust),
        ("package.json", ProjectType::Node),
        ("go.mod", ProjectType::Go),
        ("pubspec.yaml", ProjectType::Flutter),
        ("requirements.txt", ProjectType::Python),
        ("pyproject.toml", ProjectType::Python),
    ] {
        if project_path.join(marker).exists() && !stacks.contains(pt) {
            stacks.push(*pt);
        }
    }
    // Unreal markers are extension-based (*.uproject / *.uplugin / *.verse),
    // not fixed filenames, so they get their own detection.
    if crate::config::has_unreal_markers(project_path) && !stacks.contains(&ProjectType::Unreal) {
        stacks.push(ProjectType::Unreal);
    }

    sections.push(
        "# .voidignore — Generated by Void Stack\n\
         # Optimized for semantic index quality: excludes generated code,\n\
         # build artifacts, and files that don't carry business-logic semantics."
            .to_string(),
    );

    // Universal exclusions (always present)
    sections.push(format!(
        "\n# Build artifacts & dependencies\n{}",
        [
            "target/",
            "node_modules/",
            ".venv/",
            "venv/",
            "__pycache__/",
            "dist/",
            "build/",
            ".next/",
            ".nuxt/",
            ".dart_tool/",
            "vendor/",
            ".turbo/",
            "coverage/",
        ]
        .join("\n")
    ));

    // Generated code patterns
    sections.push(format!(
        "\n# Generated code\n{}",
        [
            "**/*.pb.rs",
            "**/*.pb.go",
            "**/*_pb2.py",
            "**/*_grpc.pb.go",
            "**/*.g.dart",
            "**/*.freezed.dart",
            "**/*.gen.go",
            "**/*.generated.ts",
            "**/*.d.ts",
        ]
        .join("\n")
    ));

    // Coverage & reporting
    sections.push(format!(
        "\n# Coverage & reports\n{}",
        ["lcov.info", "coverage.xml", "coverage.out", "**/*.lcov",].join("\n")
    ));

    for stack in &stacks {
        match stack {
            ProjectType::Rust => {
                sections.push(format!(
                    "\n# Rust specifics\n{}",
                    ["Cargo.lock", "**/*.log"].join("\n")
                ));
            }
            ProjectType::Go => {
                sections.push(format!(
                    "\n# Go specifics\n{}",
                    ["internal/pb/", "api/openapi/", "tmp/"].join("\n")
                ));
            }
            ProjectType::Flutter => {
                sections.push(format!(
                    "\n# Flutter platform dirs (no business logic)\n{}",
                    [
                        "android/",
                        "ios/",
                        "macos/",
                        "linux/",
                        "windows/",
                        "**/pubspec.lock",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Node => {
                sections.push(format!(
                    "\n# Node specifics\n{}",
                    [
                        "package-lock.json",
                        "yarn.lock",
                        "pnpm-lock.yaml",
                        "tsconfig.tsbuildinfo",
                        "out/",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Python => {
                sections.push(format!(
                    "\n# Python specifics\n{}",
                    ["**/*.pyc", ".pytest_cache/", "**/*.egg-info/"].join("\n")
                ));
            }
            ProjectType::Elixir => {
                sections.push(format!(
                    "\n# Elixir specifics\n{}",
                    ["_build/", "deps/", "**/*.beam", "erl_crash.dump"].join("\n")
                ));
            }
            ProjectType::Unreal => {
                sections.push(format!(
                    "\n# Unreal Engine / UEFN specifics (Plugins/ user code is kept)\n{}",
                    [
                        "Binaries/",
                        "Intermediate/",
                        "Saved/",
                        "DerivedDataCache/",
                        "*.uasset",
                        "*.umap",
                    ]
                    .join("\n")
                ));
            }
            ProjectType::Docker | ProjectType::Unknown => {}
        }
    }

    // Test fixtures & mocks (common noise for semantic search)
    sections.push(format!(
        "\n# Test fixtures & large data files\n{}",
        [
            "**/fixtures/",
            "**/testdata/",
            "**/__fixtures__/",
            "**/__snapshots__/",
        ]
        .join("\n")
    ));

    // Void Stack own artifacts
    sections.push(format!(
        "\n# Void Stack artifacts\n{}",
        ["void-stack-analysis.md", "void-stack-diagrams.drawio"].join("\n")
    ));

    let content = format!("{}\n", sections.join("\n"));

    let patterns_count = content
        .lines()
        .filter(|l| {
            let t = l.trim();
            !t.is_empty() && !t.starts_with('#')
        })
        .count();

    VoidIgnoreResult {
        content,
        patterns_count,
    }
}

/// Save generated `.voidignore` content to the project root.
pub fn save_voidignore(project_path: &Path, content: &str) -> std::io::Result<PathBuf> {
    let file_path = project_path.join(".voidignore");
    std::fs::write(&file_path, content)?;
    Ok(file_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn recount_patterns(content: &str) -> usize {
        content
            .lines()
            .filter(|l| {
                let t = l.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .count()
    }

    #[test]
    fn test_universal_patterns_always_present() {
        let dir = tempfile::tempdir().unwrap();
        let result = generate_voidignore(dir.path());

        for pattern in [
            "target/",
            "node_modules/",
            "__pycache__/",
            "**/*.pb.rs",
            "**/*.g.dart",
            "lcov.info",
            "**/fixtures/",
            "**/testdata/",
            "void-stack-analysis.md",
        ] {
            assert!(
                result.content.contains(pattern),
                "universal pattern '{}' missing from generated content",
                pattern
            );
        }
        assert!(
            result.content.starts_with("# .voidignore"),
            "content must start with the generated header"
        );
        assert!(result.patterns_count > 0, "must count at least one pattern");
    }

    #[test]
    fn test_rust_project_gets_rust_section() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname = \"x\"\n").unwrap();

        let result = generate_voidignore(dir.path());
        assert!(
            result.content.contains("# Rust specifics"),
            "Cargo.toml marker must trigger the Rust section"
        );
        assert!(result.content.contains("Cargo.lock"));
        assert!(
            !result.content.contains("package-lock.json"),
            "Node section must not appear for a pure Rust project"
        );
    }

    #[test]
    fn test_node_project_gets_node_section() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("package.json"), "{\"name\":\"x\"}").unwrap();

        let result = generate_voidignore(dir.path());
        assert!(
            result.content.contains("# Node specifics"),
            "package.json marker must trigger the Node section"
        );
        assert!(result.content.contains("pnpm-lock.yaml"));
    }

    #[test]
    fn test_multi_stack_project_gets_all_sections() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname = \"x\"\n").unwrap();
        std::fs::write(dir.path().join("package.json"), "{\"name\":\"x\"}").unwrap();
        std::fs::write(dir.path().join("go.mod"), "module example.com/x\n").unwrap();

        let result = generate_voidignore(dir.path());
        assert!(result.content.contains("# Rust specifics"), "Rust section");
        assert!(result.content.contains("# Node specifics"), "Node section");
        assert!(result.content.contains("# Go specifics"), "Go section");
        // Each section must appear exactly once even if the detector and the
        // marker scan both find the same stack.
        assert_eq!(
            result.content.matches("# Rust specifics").count(),
            1,
            "Rust section must not be duplicated"
        );
    }

    #[test]
    fn test_flutter_and_python_sections() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("pubspec.yaml"), "name: app\n").unwrap();
        std::fs::write(dir.path().join("requirements.txt"), "requests\n").unwrap();

        let result = generate_voidignore(dir.path());
        assert!(
            result.content.contains("# Flutter platform dirs"),
            "pubspec.yaml marker must trigger the Flutter section"
        );
        assert!(result.content.contains("**/pubspec.lock"));
        assert!(
            result.content.contains("# Python specifics"),
            "requirements.txt marker must trigger the Python section"
        );
        assert!(result.content.contains(".pytest_cache/"));
    }

    #[test]
    fn test_unreal_project_gets_unreal_section() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("MyGame.uproject"), "{}").unwrap();

        let result = generate_voidignore(dir.path());
        assert!(
            result.content.contains("# Unreal Engine / UEFN specifics"),
            ".uproject marker must trigger the Unreal section"
        );
        for pattern in [
            "Binaries/",
            "Intermediate/",
            "Saved/",
            "DerivedDataCache/",
            "*.uasset",
            "*.umap",
        ] {
            assert!(
                result.content.contains(pattern),
                "Unreal pattern '{}' missing from generated content",
                pattern
            );
        }
        // UEFN Plugins/ holds user code and must never appear as an ignore
        // pattern (the section header comment may mention it).
        assert!(
            !result
                .content
                .lines()
                .any(|l| !l.trim_start().starts_with('#') && l.contains("Plugins/")),
            "UEFN Plugins/ holds user code and must never be ignored"
        );
        assert_eq!(
            result.patterns_count,
            recount_patterns(&result.content),
            "patterns_count must stay consistent with the Unreal section added"
        );
    }

    #[test]
    fn test_unreal_section_triggered_by_verse_files() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("device.verse"),
            "using { /Fortnite.com/Devices }\n",
        )
        .unwrap();

        let result = generate_voidignore(dir.path());
        assert!(
            result.content.contains("# Unreal Engine / UEFN specifics"),
            "a top-level .verse file must trigger the Unreal section"
        );
        assert_eq!(
            result
                .content
                .matches("# Unreal Engine / UEFN specifics")
                .count(),
            1,
            "Unreal section must not be duplicated (detector + marker scan)"
        );
    }

    #[test]
    fn test_patterns_count_matches_non_comment_lines() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname = \"x\"\n").unwrap();

        let result = generate_voidignore(dir.path());
        assert_eq!(
            result.patterns_count,
            recount_patterns(&result.content),
            "patterns_count must equal the number of non-comment, non-empty lines"
        );
    }

    #[test]
    fn test_save_voidignore_writes_file_at_project_root() {
        let dir = tempfile::tempdir().unwrap();
        let content = "# test\ntarget/\n";

        let path = save_voidignore(dir.path(), content).expect("save must succeed");
        assert_eq!(
            path,
            dir.path().join(".voidignore"),
            "file must be created at <project>/.voidignore"
        );
        let read_back = std::fs::read_to_string(&path).expect("file must exist");
        assert_eq!(read_back, content, "content must round-trip unchanged");
    }
}
